### ISSUE TITLE
Need Documentation

### ISSUE THREAD

**Issue by Avinash-Gahlowt** [CSE-BBS-college/BBS-OneView#2]
Provide better documentation for the complete understanding of a project btw great work by BBSian.

**Comment by actuallyabhi** [comment]
**Greetings sir!** _Abhishek here from CSE (3rd year)._ Sorry for no proper documentation, project is still in early stages.
I'll explain you.
So the main idea is to replicate the functionality of AKTU Oneview for the class test which are conducted in each semester.
**Current objectives are** 

- A Responsive UI for viewing marks
- Different UI for students and teachers.
- Visualization of the scores in both views.
- A central datasheet(Google sheets) for maintaining and updating marks.
- Basic Authentication for teachers.

**Tech Stack used**
- HTML
- CSS
- Vanilla JavaScript
- Google App script(As database )

Let me know if you need any further explanation.
**Thank You!**
